name: Manual Tag Creation

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Next release tag'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  tag-creation:
    name: Tag Creation
    permissions:
      contents: write  # for Git to git push
    runs-on: cx-public-ubuntu-x64
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - name: Tag
        env:
          INPUT_TAG: ${{ github.event.inputs.tag }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          echo "$INPUT_TAG"
          echo "NEXT_VERSION=$INPUT_TAG" >> $GITHUB_ENV
          message="$INPUT_TAG: PR #$PR_NUMBER $PR_TITLE"
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${REPO}"
          git tag -a "$INPUT_TAG" -m "$message"
          git push origin "$INPUT_TAG"
